// <auto-generated />
using System;
using KooliProjekt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KooliProjekt.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250206115751_Transactions")]
    partial class Transactions
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Transactions",
                columns: table => new
                {
                    AssetID = table.Column<int>(type: "int", nullable: false),
                    AssetID1 = table.Column<int>(type: "int", nullable: false),
                    ClassID = table.Column<int>(type: "int", nullable: false),
                    Date = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Quantity = table.Column<float>(type: "real", nullable: false),
                    TransactionID = table.Column<int>(type: "int", nullable: false),
                    TransactionType = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    TransactionValue = table.Column<float>(type: "real", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Transactions", x => x.AssetID);
                    table.ForeignKey(
                        name: "FK_Transactions_Assets_AssetID1",
                        column: x => x.AssetID1,
                        principalTable: "Assets",
                        principalColumn: "AssetID",
                        onDelete: ReferentialAction.Cascade);
                });

            // Add indexes, relationships, etc. as needed
            migrationBuilder.CreateIndex(
                name: "IX_Transactions_AssetID1",
                table: "Transactions",
                column: "AssetID1");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Define how to revert the migration changes (if needed)
            migrationBuilder.DropTable(
                name: "Transactions");
        }
    }
}
