// <auto-generated />
using System;
using KooliProjekt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KooliProjekt.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250206115751_Transactions")]
    partial class Transactions
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Define the schema changes for the migration here
            migrationBuilder.CreateTable(
                name: "Transactions",
                columns: table => new
                {
                    AssetID = table.Column<int>(type: "int", nullable: false),
                    AssetID1 = table.Column<int>(type: "int", nullable: false),
                    ClassID = table.Column<int>(type: "int", nullable: false),
                    Date = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Quantity = table.Column<float>(type: "real", nullable: false),
                    TransactionID = table.Column<int>(type: "int", nullable: false),
                    TransactionType = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    TransactionValue = table.Column<float>(type: "real", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Transactions", x => x.AssetID);
                    table.ForeignKey(
                        name: "FK_Transactions_Assets_AssetID1",
                        column: x => x.AssetID1,
                        principalTable: "Assets",
                        principalColumn: "AssetID",
                        onDelete: ReferentialAction.Cascade);
                });

            // Add indexes, relationships, etc. as needed
            migrationBuilder.CreateIndex(
                name: "IX_Transactions_AssetID1",
                table: "Transactions",
                column: "AssetID1");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Define how to revert the migration changes (if needed)
            migrationBuilder.DropTable(
                name: "Transactions");
        }
        //        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        //        {
        //#pragma warning disable 612, 618
        //            modelBuilder
        //                .HasAnnotation("ProductVersion", "8.0.11")
        //                .HasAnnotation("Relational:MaxIdentifierLength", 128);

        //            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        //            modelBuilder.Entity("KooliProjekt.Data.Asset", b =>
        //                {
        //                    b.Property<int>("AssetID")
        //                        .ValueGeneratedOnAdd()
        //                        .HasColumnType("int");

        //                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetID"));

        //                    b.Property<string>("AssetDetails")
        //                        .IsRequired()
        //                        .HasColumnType("nvarchar(max)");

        //                    b.Property<string>("AssetType")
        //                        .IsRequired()
        //                        .HasMaxLength(50)
        //                        .HasColumnType("nvarchar(50)");

        //                    b.Property<int>("ClassID")
        //                        .HasColumnType("int");

        //                    b.Property<int>("InvestmentClassClassID")
        //                        .HasColumnType("int");

        //                    b.Property<string>("Name")
        //                        .IsRequired()
        //                        .HasMaxLength(100)
        //                        .HasColumnType("nvarchar(100)");

        //                    b.Property<int>("SelectedClassID")
        //                        .HasColumnType("int");

        //                    b.HasKey("AssetID");

        //                    b.HasIndex("InvestmentClassClassID");

        //                    b.ToTable("Assets");
        //                });

        //            modelBuilder.Entity("KooliProjekt.Data.Investment", b =>
        //                {
        //                    b.Property<int>("InvestmentID")
        //                        .ValueGeneratedOnAdd()
        //                        .HasColumnType("int");

        //                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvestmentID"));

        //                    b.Property<int>("AssetID")
        //                        .HasColumnType("int");

        //                    b.Property<float>("CashBalance")
        //                        .HasColumnType("real");

        //                    b.Property<DateTime>("Date")
        //                        .HasColumnType("datetime2");

        //                    b.Property<float>("MoneyInvested")
        //                        .HasColumnType("real");

        //                    b.Property<int?>("PortfolioID")
        //                        .HasColumnType("int");

        //                    b.Property<float>("Quantity")
        //                        .HasColumnType("real");

        //                    b.Property<float>("Value")
        //                        .HasColumnType("real");

        //                    b.HasKey("InvestmentID");

        //                    b.HasIndex("AssetID");

        //                    b.HasIndex("PortfolioID");

        //                    b.ToTable("Investments");
        //                });

        //            modelBuilder.Entity("KooliProjekt.Data.InvestmentClass", b =>
        //                {
        //                    b.Property<int>("ClassID")
        //                        .ValueGeneratedOnAdd()
        //                        .HasColumnType("int");

        //                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassID"));

        //                    b.Property<int?>("AssetID")
        //                        .HasColumnType("int");

        //                    b.Property<string>("Description")
        //                        .IsRequired()
        //                        .HasColumnType("nvarchar(max)");

        //                    b.Property<string>("Name")
        //                        .IsRequired()
        //                        .HasColumnType("nvarchar(max)");

        //                    b.Property<int?>("SelectedClassID")
        //                        .HasColumnType("int");

        //                    b.HasKey("ClassID");

        //                    b.ToTable("InvestmentClasses");
        //                });

        //            modelBuilder.Entity("KooliProjekt.Data.Portfolio", b =>
        //                {
        //                    b.Property<int>("PortfolioID")
        //                        .ValueGeneratedOnAdd()
        //                        .HasColumnType("int");

        //                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortfolioID"));

        //                    b.Property<float>("ChangeSinceLastMonth")
        //                        .HasColumnType("real");

        //                    b.Property<float>("ChangeSinceStart")
        //                        .HasColumnType("real");

        //                    b.Property<DateTime>("Date")
        //                        .HasColumnType("datetime2");

        //                    b.Property<float>("TotalValue")
        //                        .HasColumnType("real");

        //                    b.HasKey("PortfolioID");

        //                    b.ToTable("Portfolios");
        //                });

        //            modelBuilder.Entity("KooliProjekt.Data.Transaction", b =>
        //                {
        //                    b.Property<int>("AssetID")
        //                        .ValueGeneratedOnAdd()
        //                        .HasColumnType("int");

        //                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetID"));

        //                    b.Property<int>("AssetID1")
        //                        .HasColumnType("int");

        //                    b.Property<int>("ClassID")
        //                        .HasColumnType("int");

        //                    b.Property<DateTime>("Date")
        //                        .HasColumnType("datetime2");

        //                    b.Property<float>("Quantity")
        //                        .HasColumnType("real");

        //                    b.Property<int>("TransactionID")
        //                        .HasColumnType("int");

        //                    b.Property<string>("TransactionType")
        //                        .IsRequired()
        //                        .HasMaxLength(50)
        //                        .HasColumnType("nvarchar(50)");

        //                    b.Property<float>("TransactionValue")
        //                        .HasColumnType("real");

        //                    b.HasKey("AssetID");

        //                    b.HasIndex("AssetID1");

        //                    b.ToTable("Transactions");
        //                });

        //            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
        //                {
        //                    b.Property<string>("Id")
        //                        .HasColumnType("nvarchar(450)");

        //                    b.Property<string>("ConcurrencyStamp")
        //                        .IsConcurrencyToken()
        //                        .HasColumnType("nvarchar(max)");

        //                    b.Property<string>("Name")
        //                        .HasMaxLength(256)
        //                        .HasColumnType("nvarchar(256)");

        //                    b.Property<string>("NormalizedName")
        //                        .HasMaxLength(256)
        //                        .HasColumnType("nvarchar(256)");

        //                    b.HasKey("Id");

        //                    b.HasIndex("NormalizedName")
        //                        .IsUnique()
        //                        .HasDatabaseName("RoleNameIndex")
        //                        .HasFilter("[NormalizedName] IS NOT NULL");

        //                    b.ToTable("AspNetRoles", (string)null);
        //                });

        //            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
        //                {
        //                    b.Property<int>("Id")
        //                        .ValueGeneratedOnAdd()
        //                        .HasColumnType("int");

        //                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

        //                    b.Property<string>("ClaimType")
        //                        .HasColumnType("nvarchar(max)");

        //                    b.Property<string>("ClaimValue")
        //                        .HasColumnType("nvarchar(max)");

        //                    b.Property<string>("RoleId")
        //                        .IsRequired()
        //                        .HasColumnType("nvarchar(450)");

        //                    b.HasKey("Id");

        //                    b.HasIndex("RoleId");

        //                    b.ToTable("AspNetRoleClaims", (string)null);
        //                });

        //            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
        //                {
        //                    b.Property<string>("Id")
        //                        .HasColumnType("nvarchar(450)");

        //                    b.Property<int>("AccessFailedCount")
        //                        .HasColumnType("int");

        //                    b.Property<string>("ConcurrencyStamp")
        //                        .IsConcurrencyToken()
        //                        .HasColumnType("nvarchar(max)");

        //                    b.Property<string>("Email")
        //                        .HasMaxLength(256)
        //                        .HasColumnType("nvarchar(256)");

        //                    b.Property<bool>("EmailConfirmed")
        //                        .HasColumnType("bit");

        //                    b.Property<bool>("LockoutEnabled")
        //                        .HasColumnType("bit");

        //                    b.Property<DateTimeOffset?>("LockoutEnd")
        //                        .HasColumnType("datetimeoffset");

        //                    b.Property<string>("NormalizedEmail")
        //                        .HasMaxLength(256)
        //                        .HasColumnType("nvarchar(256)");

        //                    b.Property<string>("NormalizedUserName")
        //                        .HasMaxLength(256)
        //                        .HasColumnType("nvarchar(256)");

        //                    b.Property<string>("PasswordHash")
        //                        .HasColumnType("nvarchar(max)");

        //                    b.Property<string>("PhoneNumber")
        //                        .HasColumnType("nvarchar(max)");

        //                    b.Property<bool>("PhoneNumberConfirmed")
        //                        .HasColumnType("bit");

        //                    b.Property<string>("SecurityStamp")
        //                        .HasColumnType("nvarchar(max)");

        //                    b.Property<bool>("TwoFactorEnabled")
        //                        .HasColumnType("bit");

        //                    b.Property<string>("UserName")
        //                        .HasMaxLength(256)
        //                        .HasColumnType("nvarchar(256)");

        //                    b.HasKey("Id");

        //                    b.HasIndex("NormalizedEmail")
        //                        .HasDatabaseName("EmailIndex");

        //                    b.HasIndex("NormalizedUserName")
        //                        .IsUnique()
        //                        .HasDatabaseName("UserNameIndex")
        //                        .HasFilter("[NormalizedUserName] IS NOT NULL");

        //                    b.ToTable("AspNetUsers", (string)null);
        //                });

        //            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
        //                {
        //                    b.Property<int>("Id")
        //                        .ValueGeneratedOnAdd()
        //                        .HasColumnType("int");

        //                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

        //                    b.Property<string>("ClaimType")
        //                        .HasColumnType("nvarchar(max)");

        //                    b.Property<string>("ClaimValue")
        //                        .HasColumnType("nvarchar(max)");

        //                    b.Property<string>("UserId")
        //                        .IsRequired()
        //                        .HasColumnType("nvarchar(450)");

        //                    b.HasKey("Id");

        //                    b.HasIndex("UserId");

        //                    b.ToTable("AspNetUserClaims", (string)null);
        //                });

        //            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
        //                {
        //                    b.Property<string>("LoginProvider")
        //                        .HasMaxLength(128)
        //                        .HasColumnType("nvarchar(128)");

        //                    b.Property<string>("ProviderKey")
        //                        .HasMaxLength(128)
        //                        .HasColumnType("nvarchar(128)");

        //                    b.Property<string>("ProviderDisplayName")
        //                        .HasColumnType("nvarchar(max)");

        //                    b.Property<string>("UserId")
        //                        .IsRequired()
        //                        .HasColumnType("nvarchar(450)");

        //                    b.HasKey("LoginProvider", "ProviderKey");

        //                    b.HasIndex("UserId");

        //                    b.ToTable("AspNetUserLogins", (string)null);
        //                });

        //            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
        //                {
        //                    b.Property<string>("UserId")
        //                        .HasColumnType("nvarchar(450)");

        //                    b.Property<string>("RoleId")
        //                        .HasColumnType("nvarchar(450)");

        //                    b.HasKey("UserId", "RoleId");

        //                    b.HasIndex("RoleId");

        //                    b.ToTable("AspNetUserRoles", (string)null);
        //                });

        //            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
        //                {
        //                    b.Property<string>("UserId")
        //                        .HasColumnType("nvarchar(450)");

        //                    b.Property<string>("LoginProvider")
        //                        .HasMaxLength(128)
        //                        .HasColumnType("nvarchar(128)");

        //                    b.Property<string>("Name")
        //                        .HasMaxLength(128)
        //                        .HasColumnType("nvarchar(128)");

        //                    b.Property<string>("Value")
        //                        .HasColumnType("nvarchar(max)");

        //                    b.HasKey("UserId", "LoginProvider", "Name");

        //                    b.ToTable("AspNetUserTokens", (string)null);
        //                });

        //            modelBuilder.Entity("KooliProjekt.Data.Asset", b =>
        //                {
        //                    b.HasOne("KooliProjekt.Data.InvestmentClass", "InvestmentClass")
        //                        .WithMany("Assets")
        //                        .HasForeignKey("InvestmentClassClassID")
        //                        .OnDelete(DeleteBehavior.Cascade)
        //                        .IsRequired();

        //                    b.Navigation("InvestmentClass");
        //                });

        //            modelBuilder.Entity("KooliProjekt.Data.Investment", b =>
        //                {
        //                    b.HasOne("KooliProjekt.Data.Asset", "Asset")
        //                        .WithMany("Investments")
        //                        .HasForeignKey("AssetID")
        //                        .OnDelete(DeleteBehavior.Cascade)
        //                        .IsRequired();

        //                    b.HasOne("KooliProjekt.Data.Portfolio", null)
        //                        .WithMany("Investments")
        //                        .HasForeignKey("PortfolioID");

        //                    b.Navigation("Asset");
        //                });

        //            modelBuilder.Entity("KooliProjekt.Data.Transaction", b =>
        //                {
        //                    b.HasOne("KooliProjekt.Data.Asset", "Asset")
        //                        .WithMany("Transactions")
        //                        .HasForeignKey("AssetID1")
        //                        .OnDelete(DeleteBehavior.Cascade)
        //                        .IsRequired();

        //                    b.Navigation("Asset");
        //                });

        //            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
        //                {
        //                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
        //                        .WithMany()
        //                        .HasForeignKey("RoleId")
        //                        .OnDelete(DeleteBehavior.Cascade)
        //                        .IsRequired();
        //                });

        //            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
        //                {
        //                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
        //                        .WithMany()
        //                        .HasForeignKey("UserId")
        //                        .OnDelete(DeleteBehavior.Cascade)
        //                        .IsRequired();
        //                });

        //            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
        //                {
        //                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
        //                        .WithMany()
        //                        .HasForeignKey("UserId")
        //                        .OnDelete(DeleteBehavior.Cascade)
        //                        .IsRequired();
        //                });

        //            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
        //                {
        //                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
        //                        .WithMany()
        //                        .HasForeignKey("RoleId")
        //                        .OnDelete(DeleteBehavior.Cascade)
        //                        .IsRequired();

        //                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
        //                        .WithMany()
        //                        .HasForeignKey("UserId")
        //                        .OnDelete(DeleteBehavior.Cascade)
        //                        .IsRequired();
        //                });

        //            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
        //                {
        //                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
        //                        .WithMany()
        //                        .HasForeignKey("UserId")
        //                        .OnDelete(DeleteBehavior.Cascade)
        //                        .IsRequired();
        //                });

        //            modelBuilder.Entity("KooliProjekt.Data.Asset", b =>
        //                {
        //                    b.Navigation("Investments");

        //                    b.Navigation("Transactions");
        //                });

        //            modelBuilder.Entity("KooliProjekt.Data.InvestmentClass", b =>
        //                {
        //                    b.Navigation("Assets");
        //                });

        //            modelBuilder.Entity("KooliProjekt.Data.Portfolio", b =>
        //                {
        //                    b.Navigation("Investments");
        //                });
        //#pragma warning restore 612, 618
        //        }
        //    } ///
    }
}
